### ISSUE TITLE
Lexer error on := inside begin/end block.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/sqlparse#146]
```erlang
sqlparse:parsetree(<<"BEGIN :SQLT_DAT_OUT_RESULT := TO_DATE(SYSDATE); END;">>).
{lex_error,{1,sql_lex,{illegal,":="}}}
```

However running it against oracle works as expected.

**Comment by stoch** [comment]
@walter-weinmann We cannot really say that it makes no sense. We occasionally want to test PL-SQL functions like this back-end for a web API in DDerl:

![image](https://user-images.githubusercontent.com/1941407/47743604-bb87da00-dc7f-11e8-956f-f4736fd1973d.png)

For which a sample request/response gives:

![image](https://user-images.githubusercontent.com/1941407/47743685-e7a35b00-dc7f-11e8-9085-9db4ab01297d.png)

@acautin This was taken on ZHH Management today. Did it work because we are falling back to sending the request anyways or because we use an older parser?

@walter-weinmann if the plsql_parser could understand ':=' would it then fail on '=>'  (which is not really needed here) ?

**Comment by walter-weinmann** [comment]
I'm working on the following extension:

![image](https://user-images.githubusercontent.com/1956149/47745803-cbee8380-dc84-11e8-8be1-4c53af60f4f1.png)

It will not support the `=>` operator.

**Comment by acautin** [comment]
@stoch it works because at the moment if the sqlparse fails, we use the regexp to find the parameters and since they have the correct names they were properly detected. After we try to execute the query against oracle regardless if it is correctly parsed or not.

**Comment by walter-weinmann** [comment]
@stoch & @acautin : I think we can close this one.

**Comment by acautin** [comment]
👍

**Comment by stoch** [comment]
Validated using:

```
BEGIN
  :SQLT_CHR_OUT_RESULT := pkg_aaa_cpro.aaa_barring_msisdn_post(
    'EASYPAY',
    :SQLT_CHR_MSISDN,
    :SQLT_CHR_REQUESTOR,
    :SQLT_CHR_REMARK
  );
END;
```


![image](https://user-images.githubusercontent.com/1941407/48936557-8a5f9a00-ef0b-11e8-84c6-d17b9b936847.png)
